name: Push Latest NiFi to DockerHub
on:
  push:
    branches:
      # - 'traice/nifi-*' 
      - 'nifi-*'

env:
  NIFI_IMAGE: apache-nifi
  NIFI_IMAGE_TAG: 1.16.3

jobs:
  push-nifi-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TRAICE_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TRAICE_DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd nifi-docker/dockerhub
          docker build -t ${{ secrets.TRAICE_DOCKERHUB_USERNAME }}/${NIFI_IMAGE}:${NIFI_IMAGE_TAG} .
          docker images
        
      - name: Push Docker image
        run: docker push ${{ secrets.TRAICE_DOCKERHUB_USERNAME }}/${NIFI_IMAGE}:${NIFI_IMAGE_TAG}